{application,exads,
             [{registered,[]},
              {description,"exads"},
              {applications,[kernel,stdlib,elixir,logger]},
              {vsn,"0.0.1"},
              {modules,['Elixir.BinarySearchTree','Elixir.Exads',
                        'Elixir.Exads.DataStructures.PriorityQueue',
                        'Elixir.Exads.DataStructures.Queue',
                        'Elixir.Exads.DataStructures.Stack']}]}.